### PR TITLE
Remove unneded null pointer checks when deleting

### LINKED ISSUE #2: Remove unnecessary null pointer checks
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [durable_log](https://github.com/rescrv/Consus/blob/da9f9d78d0f500e7e06e93cf39fab590ac521820/txman/durable_log.cc#L102 "Destructor for durable_log")
- [leveldb_datalayer](https://github.com/rescrv/Consus/blob/da9f9d78d0f500e7e06e93cf39fab590ac521820/kvs/leveldb_datalayer.cc#L151 "Destructor for leveldb_datalayer")

### PR DESCRIPTION
**Pull request by danielcompton**
https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null

Fixes #2

### CODE REVIEW

**Comment by rescrv** [comment]
Sorry.  Bad habit maintained by times I work with C/malloc/free.

Can I get you to recommit the change with "git commit -s"?  Since you started the pull request I added a SIGNED-OFF-BY line to base of the repo.  There is some behind-the-scenes interest in Consus that would like to make sure the BSD license gets preserved for all.

**Comment by rescrv** [comment]
(and apologies for asking you to re-do something for the sake of something not code related)

**Comment by danielcompton** [comment]
Not a problem at all, have re-pushed.

**Comment by rescrv** [comment]
Thank you!

**Comment by elfring** [comment]
Thanks for your small source code improvement.

**Comment by danielcompton** [comment]
This is a curl command to check the DCO:

```sh
curl --silent "https://api.github.com/repos/rescrv/Consus/pulls/3/commits" \
  | jq '[.[] | .commit.message | contains("Signed-off-by:")] | all'
```

**Comment by rescrv** [comment]
I generally check out the branch on the command line before merging anyway, but thank you for the command.

**Comment by danielcompton** [comment]
There's also https://probot.github.io/apps/dco/ which can automatically check for a DCO.

**Pull request merged**
